## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.random.randint(10, size=10)
print(arr)
arr[(3<arr) & (arr<8)] *= -1
print(arr)

[3 4 2 6 1 6 7 7 1 5]
[ 3 -4  2 -6  1 -6 -7 -7  1 -5]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = np.random.randint(10, size=10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[3 4 5 2 3 0 9 4 4 8]
[3 4 5 2 3 0 0 4 4 8]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
arr = np.random.randint(10, size=(2,3))
print(arr)
arr1 = np.random.randint(10, size=10)
arr2 = np.random.randint(10, size=10)

[[3 7 5]
 [2 5 2]]


In [5]:
x = np.tile(arr[0], len(arr[1]))
x

array([3, 7, 5, 3, 7, 5, 3, 7, 5])

In [6]:
y = np.repeat(arr[1], len(arr[0]))
y

array([2, 2, 2, 5, 5, 5, 2, 2, 2])

In [7]:
output = np.transpose([x,y])
output

array([[3, 2],
       [7, 2],
       [5, 2],
       [3, 5],
       [7, 5],
       [5, 5],
       [3, 2],
       [7, 2],
       [5, 2]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
A = np.random.randint(5, size=(8,3))
B = np.random.randint(5, size=(2,2))
A

array([[1, 0, 4],
       [4, 0, 4],
       [1, 3, 1],
       [0, 4, 2],
       [4, 3, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 4, 4]])

In [9]:
B

array([[2, 2],
       [2, 1]])

In [10]:
# Находим все уникальные элементы во 2-й матрице
C = B.reshape(-1)
print(C)
uniq = np.unique(C)
uniq

[2 2 2 1]


array([1, 2])

In [11]:
isin = np.isin(A, uniq)
print(isin)

[[ True False False]
 [False False False]
 [ True False  True]
 [False False  True]
 [False False False]
 [False  True False]
 [ True  True  True]
 [False False False]]


In [12]:
E = np.logical_and.reduce(isin, axis=1)
E

array([False, False, False, False, False, False,  True, False])

In [13]:
answer = A[E]
answer

array([[1, 1, 1]])

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [14]:
mtx = np.random.randint(4, size=(10,3))
mtx

array([[1, 0, 0],
       [0, 2, 2],
       [2, 2, 0],
       [0, 2, 3],
       [3, 0, 2],
       [3, 0, 3],
       [2, 1, 2],
       [0, 3, 2],
       [0, 2, 0],
       [3, 2, 3]])

In [15]:
E = np.logical_or.reduce(mtx[:,:-1]!=mtx[:,1:], axis=1)
print(E)
mtx = mtx[E]
mtx

[ True  True  True  True  True  True  True  True  True  True]


array([[1, 0, 0],
       [0, 2, 2],
       [2, 2, 0],
       [0, 2, 3],
       [3, 0, 2],
       [3, 0, 3],
       [2, 1, 2],
       [0, 3, 2],
       [0, 2, 0],
       [3, 2, 3]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [16]:
mtx = np.random.randint(2, size=(5,3))
print(mtx)

[[1 1 0]
 [0 1 1]
 [1 1 0]
 [0 1 0]
 [1 0 0]]


In [17]:
np.unique(mtx, axis=0)

array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [18]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
X

[[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

In [19]:
# Без использования numpy
shape0, shape1 = len(X), len(X[0])
for i in range(min(shape0, shape1)):
    prod = 1
    if (X[i][i]!=0):
        prod *= X[i][i]
if (i==1):  # Если все элементы равны 0
    print(0)
else:
    print(prod)

3


In [20]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

In [21]:
# C использованием numpy
if (~np.any(X)):  # Если матрица состоит только из 0
    print(0)
else:
    print(np.prod(np.where(np.diag(X)!=0, np.diag(X), 1)))

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [22]:
# Без использования numpy
from functools import reduce

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
reduce(lambda x, y : x and y, map(lambda p, q: p == q, x, y), True)

False

In [23]:
# C использованием numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

np.isin(x,y).all()

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [24]:
# Без использования numpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_elem = max([x[i] for i in range(1, len(x)) if x[i-1]==0])
max_elem

5

In [25]:
# C использованием numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_elem = np.max(x[np.where(x[:-1] == 0)[0] + 1])           
max_elem

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [26]:
# Без использования numpy
x = [2, 2, 2, 3, 3, 3, 5]
print((list(set(x)), [x.count(i) for i in set(x)]))

([2, 3, 5], [3, 3, 1])


In [27]:
# C использованием numpy
x = np.array([2, 2, 3, 2, 3, 3, 5])
print((np.unique(x), np.delete(np.bincount(x), np.where(np.bincount(x)==0)[0])))

(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [28]:
from scipy.spatial import distance

X = [(35.0456, -85.2672), (12, 33), (12, 36), (61, 37)]
Y = [(35.9728, -83.9422), (31, 44), (52, 61), (73, 38)]
print(distance.cdist(X, Y, 'euclidean'))

[[  1.6171966  129.3304909  147.24654656 128.97805656]
 [119.37408965  21.9544984   48.82622246  61.20457499]
 [122.31445737  20.61552813  47.16990566  61.03277808]
 [123.50456057  30.8058436   25.63201124  12.04159458]]


In [29]:
# Без использования numpy
print(list(map(lambda x, y: np.sqrt(np.sum(np.square(np.array(x) - np.array(y)))), X, Y)))

[1.6171965990565296, 21.95449840010015, 47.16990566028302, 12.041594578792296]


In [30]:
# C использованием numpy
print(np.sqrt(np.sum(np.square(np.array(X) - np.array(Y)), axis=1)))

[ 1.6171966  21.9544984  47.16990566 12.04159458]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [31]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [32]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [33]:
average_calories = np.average(calorie_stats) - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [34]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [35]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [36]:
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [37]:
nth_percentile = np.percentile(calorie_stats, 3.28948)
nth_percentile

60.000096

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [38]:
more_calories = len(calorie_stats[calorie_stats > 60]) / len(calorie_stats) * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [39]:
calorie_std = np.std(calorie_stats)
calorie_std
# В данном случае, стандарнтое отклонение сильно отличается от нуля, что означает,
# что разброс очень велик. Это затруднят объективную оценку, так что мы не можем сделать 
# такое обобщение

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [40]:
# Продукт нашей фирмы содержит практически в 2 раза меньше колорий по сравнению со средней калорийностью этого же продукта на рынке
# При этом калорий в нем меньше, чем в абсолютном большинстве (около 96%).
# Можно увеличить объем выборки, добавив новые фирмы, это снизит стандартное отклонение, 
# и позволит более точно оценить наш продукт