## numpy Library Exercises

In [1]:
import numpy as np

**1.** Given a random array, flip the sign of elements with values between 3 and 8

In [2]:
arr = np.random.randint(10, size=10)
print(arr)
arr[(3<arr) & (arr<8)] *= -1
print(arr)

[3 4 2 6 1 6 7 7 1 5]
[ 3 -4  2 -6  1 -6 -7 -7  1 -5]


**2.** Replace the maximum element of a random array with 0

In [3]:
arr = np.random.randint(10, size=10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[3 4 5 2 3 0 9 4 4 8]
[3 4 5 2 3 0 0 4 4 8]


**3.** Construct the Cartesian product of arrays (all combinations involving each element). The input is a two-dimensional array

In [4]:
arr = np.random.randint(10, size=(2,3))
print(arr)
arr1 = np.random.randint(10, size=10)
arr2 = np.random.randint(10, size=10)

[[3 7 5]
 [2 5 2]]


In [5]:
x = np.tile(arr[0], len(arr[1]))
x

array([3, 7, 5, 3, 7, 5, 3, 7, 5])

In [6]:
y = np.repeat(arr[1], len(arr[0]))
y

array([2, 2, 2, 5, 5, 5, 2, 2, 2])

In [7]:
output = np.transpose([x,y])
output

array([[3, 2],
       [7, 2],
       [5, 2],
       [3, 5],
       [7, 5],
       [5, 5],
       [3, 2],
       [7, 2],
       [5, 2]])

**4.** Two arrays, A (8x3) and B (2x2), are given. Find the rows in A that contain elements from each row of B, regardless of the order of elements within the rows of B

In [8]:
A = np.random.randint(5, size=(8,3))
B = np.random.randint(5, size=(2,2))
A

array([[1, 0, 4],
       [4, 0, 4],
       [1, 3, 1],
       [0, 4, 2],
       [4, 3, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 4, 4]])

In [9]:
B

array([[2, 2],
       [2, 1]])

In [10]:
# Find all unique elements in the second matrix
C = B.reshape(-1)
print(C)
uniq = np.unique(C)
uniq

[2 2 2 1]


array([1, 2])

In [11]:
isin = np.isin(A, uniq)
print(isin)

[[ True False False]
 [False False False]
 [ True False  True]
 [False False  True]
 [False False False]
 [False  True False]
 [ True  True  True]
 [False False False]]


In [12]:
E = np.logical_and.reduce(isin, axis=1)
E

array([False, False, False, False, False, False,  True, False])

In [13]:
answer = A[E]
answer

array([[1, 1, 1]])

**5.** Given a 10x3 matrix, find the rows containing unequal values (for example, the row [2, 2, 3] is kept, while the row [3, 3, 3] is removed)

In [14]:
mtx = np.random.randint(4, size=(10,3))
mtx

array([[1, 0, 0],
       [0, 2, 2],
       [2, 2, 0],
       [0, 2, 3],
       [3, 0, 2],
       [3, 0, 3],
       [2, 1, 2],
       [0, 3, 2],
       [0, 2, 0],
       [3, 2, 3]])

In [15]:
E = np.logical_or.reduce(mtx[:,:-1]!=mtx[:,1:], axis=1)
print(E)
mtx = mtx[E]
mtx

[ True  True  True  True  True  True  True  True  True  True]


array([[1, 0, 0],
       [0, 2, 2],
       [2, 2, 0],
       [0, 2, 3],
       [3, 0, 2],
       [3, 0, 3],
       [2, 1, 2],
       [0, 3, 2],
       [0, 2, 0],
       [3, 2, 3]])

**6.** Given a two-dimensional array, remove the duplicate rows

In [16]:
mtx = np.random.randint(2, size=(5,3))
print(mtx)

[[1 1 0]
 [0 1 1]
 [1 1 0]
 [0 1 0]
 [1 0 0]]


In [17]:
np.unique(mtx, axis=0)

array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

______
______

For each of the following tasks (1–5), provide two implementations: one without using NumPy (assume that inputs or outputs requiring NumPy arrays will instead be standard Python lists), and a second that is fully vectorized using NumPy (avoiding Python loops, `map`, or list comprehensions).

**Note 1.** You may assume that all objects involved are non-empty (e.g., in **Task 1**, the matrix diagonal contains non-zero elements).

**Note 2.** For most tasks, the solution requires no more than 1–2 lines of code

___

* __Task 1__: Calculate the product of the non-zero elements on the diagonal of a rectangular matrix. 
For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]), the answer is 3

In [18]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
X

[[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

In [19]:
# Without using numpy
shape0, shape1 = len(X), len(X[0])
for i in range(min(shape0, shape1)):
    prod = 1
    if (X[i][i]!=0):
        prod *= X[i][i]
if (i==1):  # If all elements are equal to 0
    print(0)
else:
    print(prod)

3


In [20]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

In [21]:
# Using numpy
if (~np.any(X)): # If the matrix consists only of 0s0
    print(0)
else:
    print(np.prod(np.where(np.diag(X)!=0, np.diag(X), 1)))

3


* __Task 2__: Given two vectors x and y, determine whether they represent the same multiset. 
For example, for x = np.array([1, 2, 2, 4]) and y = np.array([4, 2, 1, 2]), the answer is True

In [22]:
# Without using numpy
from functools import reduce

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
reduce(lambda x, y : x and y, map(lambda p, q: p == q, x, y), True)

False

In [23]:
# Using numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

np.isin(x,y).all()

True

* __Task 3__: Find the maximum element in vector x among the elements preceded by a zero.
For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]), the answer is 5

In [24]:
# Without using numpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_elem = max([x[i] for i in range(1, len(x)) if x[i-1]==0])
max_elem

5

In [25]:
# Using numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_elem = np.max(x[np.where(x[:-1] == 0)[0] + 1])           
max_elem

5

* __Task 4__: Implement run-length encoding. Given a vector `x`, return a tuple of two vectors of equal length: the first contains the values, and the second contains the number of times each value is repeated.
For example, for `x = np.array([2, 2, 2, 3, 3, 3, 5])`, the result is `(np.array([2, 3, 5]), np.array([3, 3, 1]))`

In [26]:
# Without using numpy
x = [2, 2, 2, 3, 3, 3, 5]
print((list(set(x)), [x.count(i) for i in set(x)]))

([2, 3, 5], [3, 3, 1])


In [27]:
# Using numpy
x = np.array([2, 2, 3, 2, 3, 3, 5])
print((np.unique(x), np.delete(np.bincount(x), np.where(np.bincount(x)==0)[0])))

(array([2, 3, 5]), array([3, 3, 1]))


* __Task 5__: Given two samples of objects, X and Y, calculate the matrix of Euclidean distances between the objects. Compare the execution speed with the `scipy.spatial.distance.cdist` function

In [28]:
from scipy.spatial import distance

X = [(35.0456, -85.2672), (12, 33), (12, 36), (61, 37)]
Y = [(35.9728, -83.9422), (31, 44), (52, 61), (73, 38)]
print(distance.cdist(X, Y, 'euclidean'))

[[  1.6171966  129.3304909  147.24654656 128.97805656]
 [119.37408965  21.9544984   48.82622246  61.20457499]
 [122.31445737  20.61552813  47.16990566  61.03277808]
 [123.50456057  30.8058436   25.63201124  12.04159458]]


In [29]:
# Without using numpy
print(list(map(lambda x, y: np.sqrt(np.sum(np.square(np.array(x) - np.array(y)))), X, Y)))

[1.6171965990565296, 21.95449840010015, 47.16990566028302, 12.041594578792296]


In [30]:
# Using numpy
print(np.sqrt(np.sum(np.square(np.array(X) - np.array(Y)), axis=1)))

[ 1.6171966  21.9544984  47.16990566 12.04159458]


_______
________

* __Task 6__: CrunchieMunchies

You work in the marketing department of the food company MyCrunch, which is developing a new type of tasty, healthy cereal called **CrunchieMunchies**.

You want to demonstrate to consumers just how healthy your cereal is compared to other leading brands, so you have gathered nutritional data on several different competitors.

Your task is to use NumPy calculations to analyze this data and prove that **CrunchieMunchies** are the healthiest choice for consumers

In [31]:
import numpy as np

1. Examine the file cereal.csv. This file contains calorie counts for various brands of cereal. Load the data from the file and save it as calorie_stats

In [32]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. A single serving of CrunchieMunchies contains 60 calories. By how much does the average calorie count of your competitors exceed this?

Store the answer in the variable `average_calories` and print the variable to the terminal

In [33]:
average_calories = np.average(calorie_stats) - 60
average_calories

46.883116883116884

3. Does the average calorie count accurately reflect the distribution of the dataset? Let's sort the data and see.

Sort the data and save the result in the variable `calorie_stats_sorted`. Print the sorted information

In [34]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. It appears that most values are above the mean. Let's see if the median is the most appropriate measure for this dataset.

Calculate the median of the dataset and store your answer in `median_calories`. Print the median so you can see how it compares to the mean

In [35]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. While the median shows that at least half of our values are above 100 calories, it would be more impressive to show that a significant portion of competitors have a higher calorie count than CrunchieMunchies.

Calculate and print various percentiles until you find the lowest percentile that exceeds 60 calories. Store this value in the variable `nth_percentile`

In [36]:
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [37]:
nth_percentile = np.percentile(calorie_stats, 3.28948)
nth_percentile

60.000096

6. Although the percentile shows us that most competitors have a much higher calorie count, it is an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Store your answer in the variable `more_calories` and print it

In [38]:
more_calories = len(calorie_stats[calorie_stats > 60]) / len(calorie_stats) * 100
more_calories

96.1038961038961

7. That is indeed a high percentage. This will be very useful when we promote CrunchieMunchies. But one question remains: how large is the variation in the dataset? Can we generalize that most cereals contain around 100 calories, or is the spread even wider?

Calculate the degree of variation by finding the standard deviation; store your answer in `calorie_std` and print it to the terminal. How can we incorporate this value into our analysis?

In [39]:
calorie_std = np.std(calorie_stats)
calorie_std
# In this case, the standard deviation differs significantly from zero, which means
# that the dispersion is very high. This makes objective assessment difficult, so we cannot make
# such a generalization

19.35718533390827

8. Write a short paragraph summarizing your conclusions and how you believe this data could be used to benefit Mycrunch when marketing CrunchieMunchies

In [40]:
# Our company's product contains nearly half the calories of the market average for the same product.
# Moreover, it has a lower calorie count than the vast majority (approximately 96%) of similar products.
# Increasing the sample size by adding more companies would reduce the standard deviation
# and allow for a more accurate assessment of our product